name = "MP4-LibMP4v2"
license = "perl_5"
module_maker = "ModuleBuild"
badges = ['github-actions/test']
[build]
build_class = "builder::MyBuilder"
[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'builder', 'ext']
